### ISSUE TITLE
'std::bad_alloc' error

### ISSUE THREAD

**Issue by hidvegin** [bcgsc/ntHits#10]
Hello!

I tried ntHits to use with my 10x Genomics linked reads and Illumina PE150 reads. I used this parameters:

`ntHits -b36 -k96 -t80 --outbloom --solid --pref=lculinarisk96 @reads.in`

And I got this error:

```
Reapeat profile estimated using ntCard in (sec): 4.0532
Errors k-mer coverage: 0
Approximate# of distinct k-mers: 0
Approximate# of solid k-mers: 0
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
/var/spool/slurmd/job19727/slurm_script: line 13: 210989 Aborted                 nthits -b36 -k96 -t80 --outbloom --solid --pref=lculinarisk96 @reads.in
```

I used 80 CPU and 280 GB RAM. How could I solve this issue?

**Comment by lcoombe** [comment]
Hi @hidvegin,

It looks to me like you're running out of memory. 
I'd try lowering `-b`, which will lead to less memory being used, and see if that solves the problem. It also wouldn't hurt to add a `/usr/bin/time` to your command to get a measure of how much memory was being used at the peak.

Hope that helps!
Lauren

**Comment by hidvegin** [comment]
Hello @lcoombe,

Thank you for your answer.

I will try lowering `-b`. With `-b36` I got this message from `/usr/bin/time`:

```
Reapeat profile estimated using ntCard in (sec): 4.2004
Errors k-mer coverage: 0
Approximate# of distinct k-mers: 0
Approximate# of solid k-mers: 0
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
3.12user 1.27system 0:04.22elapsed 104%CPU (0avgtext+0avgdata 528276maxresident)k
0inputs+8outputs (0major+132229minor)pagefaults 0swaps
```

**Comment by hidvegin** [comment]
I tried `-b26`, -`b16` and `-b6` but I got the same error message what was at `-b36`.

**Comment by jowong4** [comment]
Hi, Can you check if you do have 280GB unused ram at the time of starting ntHits. The program is terminating in 4seconds which is unlikely. Can you also check if the input file format is correct?

**Comment by hidvegin** [comment]
Hi @jowong4,

Thank you for your answer. I use a file list (reads.in). This is the file list:

```
$HOME/output/trimmed/10x/LC001_trimmed.fq.gz
$HOME/output/trimmed/10x/LC002_trimmed.fq.gz
$HOME/output/trimmed/10x/LC003_trimmed.fq.gz
$HOME/output/trimmed/10x/LC004_trimmed.fq.gz
$HOME/output/trimmed/Illumina/LC002_L2A_trimmed_1.fq.gz
$HOME/output/trimmed/Illumina/LC002_L2A_trimmed_2.fq.gz
$HOME/output/trimmed/Illumina/LC002_L3A_trimmed_1.fq.gz
$HOME/output/trimmed/Illumina/LC002_L3A_trimmed_2.fq.gz
$HOME/output/trimmed/Illumina/LC002_L4A_trimmed_1.fq.gz
$HOME/output/trimmed/Illumina/LC002_L4A_trimmed_2.fq.gz
$HOME/output/trimmed/Illumina/LC002_L4B_trimmed_1.fq.gz
$HOME/output/trimmed/Illumina/LC002_L4B_trimmed_2.fq.gz
```
I use a HPC with SLURM control. The SLURM can allocate 3500 MB RAM/CPU. In this case I used 80 CPU with 280 GB RAM. I think all of the 280 GB RAM are unused.

**Comment by jowong4** [comment]
I suspect that your scheduler is not giving you a contiguous block of 280GB of ram. Can you takes the first 1000 lines of your first file and make a new input, and see if you can run ntHits with that file using one cpu core?

**Comment by hidvegin** [comment]
I changed my list file. The error was the `$HOME`. I should change `$HOME` to the exactly home directory `/home/username/`. I do not know this is why a problem because until this time worked. After the change, ntHits is working.

**Comment by lcoombe** [comment]
Huh interesting - Thanks for reporting your solution, @hidvegin!
